"""migration models to alembic2

Revision ID: 339cf6f41713
Revises: add_status_check_20251021_04
Create Date: 2025-10-22 13:17:20.699118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '339cf6f41713'
down_revision: Union[str, Sequence[str], None] = 'add_status_check_20251021_04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='顯示排序')
    op.alter_column('dish', 'name_zh',
               existing_type=sa.TEXT(),
               comment='中文名稱',
               existing_comment='中文菜名',
               existing_nullable=False)
    op.alter_column('dish', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='顯示排序')
    op.create_index('ix_dish_category_id', 'dish', ['category_id'], unique=False)
    op.alter_column('dish_detail', 'tags',
               existing_type=sa.TEXT(),
               comment='餐點標籤 (例如: 素食, 豬肉, 辣)',
               existing_comment='餐點標籤',
               existing_nullable=True)
    op.alter_column('dish_price', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='售價',
               existing_comment='金額',
               existing_nullable=True)
    op.create_index('ix_dish_price_dish_id', 'dish_price', ['dish_id'], unique=False)
    op.alter_column('dish_translation', 'name',
               existing_type=sa.TEXT(),
               comment='對應語言名稱',
               existing_comment='對應語言菜名',
               existing_nullable=False)
    op.create_index('ix_dish_translation_dish_id', 'dish_translation', ['dish_id'], unique=False)
    op.create_index('ix_dish_translation_lang', 'dish_translation', ['lang'], unique=False)
    op.alter_column('order_item', 'dish_id',
               existing_type=sa.BIGINT(),
               comment='菜色ID (可能為空，因歷史資料可能被刪除)',
               existing_comment='菜色ID',
               existing_nullable=True)
    op.alter_column('order_item', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='額外資訊 (例如: 圖片URL)',
               existing_comment='額外資訊',
               existing_nullable=True)

    # Clean up invalid dish_id references before adding foreign key
    op.execute("""
        UPDATE order_item
        SET dish_id = NULL
        WHERE dish_id IS NOT NULL
        AND dish_id NOT IN (SELECT dish_id FROM dish)
    """)

    op.create_foreign_key(None, 'order_item', 'dish', ['dish_id'], ['dish_id'], ondelete='SET NULL')
    op.alter_column('orders', 'cart_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='下單時購物車快照',
               existing_nullable=True)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.alter_column('set_item', 'set_id',
               existing_type=sa.BIGINT(),
               comment='套餐ID(父項)',
               existing_comment='套餐ID(父菜)',
               existing_nullable=False)
    op.alter_column('set_item', 'item_id',
               existing_type=sa.BIGINT(),
               comment='子項ID',
               existing_comment='子菜ID',
               existing_nullable=False)
    op.alter_column('set_item', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='顯示排序')
    op.create_index('ix_set_item_item_id', 'set_item', ['item_id'], unique=False)
    op.create_index('ix_set_item_set_id', 'set_item', ['set_id'], unique=False)

    # Convert session_id columns from VARCHAR(36) to UUID
    # Step 1: Drop foreign key constraint from orders table
    op.drop_constraint('orders_session_id_fkey', 'orders', type_='foreignkey')

    # Step 2: Convert both columns to UUID with explicit USING clause
    op.execute('ALTER TABLE user_session ALTER COLUMN session_id TYPE UUID USING session_id::uuid')
    op.execute('ALTER TABLE orders ALTER COLUMN session_id TYPE UUID USING session_id::uuid')

    # Step 3: Recreate foreign key constraint
    op.create_foreign_key('orders_session_id_fkey', 'orders', 'user_session', ['session_id'], ['session_id'], ondelete='SET NULL')

    op.alter_column('user_session', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Session 任意資料 (含購物車)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_session', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Session 任意資料 (含購物車)',
               existing_nullable=True)

    # Convert session_id columns back from UUID to VARCHAR(36)
    # Step 1: Drop foreign key constraint
    op.drop_constraint('orders_session_id_fkey', 'orders', type_='foreignkey')

    # Step 2: Convert both columns back to VARCHAR(36)
    op.execute('ALTER TABLE user_session ALTER COLUMN session_id TYPE VARCHAR(36) USING session_id::text')
    op.execute('ALTER TABLE orders ALTER COLUMN session_id TYPE VARCHAR(36) USING session_id::text')

    # Step 3: Recreate foreign key constraint
    op.create_foreign_key('orders_session_id_fkey', 'orders', 'user_session', ['session_id'], ['session_id'], ondelete='SET NULL')

    op.drop_index('ix_set_item_set_id', table_name='set_item')
    op.drop_index('ix_set_item_item_id', table_name='set_item')
    op.alter_column('set_item', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='顯示排序')
    op.alter_column('set_item', 'item_id',
               existing_type=sa.BIGINT(),
               comment='子菜ID',
               existing_comment='子項ID',
               existing_nullable=False)
    op.alter_column('set_item', 'set_id',
               existing_type=sa.BIGINT(),
               comment='套餐ID(父菜)',
               existing_comment='套餐ID(父項)',
               existing_nullable=False)
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.alter_column('orders', 'cart_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='下單時購物車快照',
               existing_nullable=True)
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.alter_column('order_item', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment='額外資訊',
               existing_comment='額外資訊 (例如: 圖片URL)',
               existing_nullable=True)
    op.alter_column('order_item', 'dish_id',
               existing_type=sa.BIGINT(),
               comment='菜色ID',
               existing_comment='菜色ID (可能為空，因歷史資料可能被刪除)',
               existing_nullable=True)
    op.drop_index('ix_dish_translation_lang', table_name='dish_translation')
    op.drop_index('ix_dish_translation_dish_id', table_name='dish_translation')
    op.alter_column('dish_translation', 'name',
               existing_type=sa.TEXT(),
               comment='對應語言菜名',
               existing_comment='對應語言名稱',
               existing_nullable=False)
    op.drop_index('ix_dish_price_dish_id', table_name='dish_price')
    op.alter_column('dish_price', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='金額',
               existing_comment='售價',
               existing_nullable=True)
    op.alter_column('dish_detail', 'tags',
               existing_type=sa.TEXT(),
               comment='餐點標籤',
               existing_comment='餐點標籤 (例如: 素食, 豬肉, 辣)',
               existing_nullable=True)
    op.drop_index('ix_dish_category_id', table_name='dish')
    op.alter_column('dish', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='顯示排序')
    op.alter_column('dish', 'name_zh',
               existing_type=sa.TEXT(),
               comment='中文菜名',
               existing_comment='中文名稱',
               existing_nullable=False)
    op.alter_column('category', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='顯示排序')
    # ### end Alembic commands ###
