"""create menu tables

Revision ID: e691d383068d
Revises: 
Create Date: 2025-10-08 16:19:38.590047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e691d383068d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name_zh', sa.Text(), nullable=False, comment='中文名稱'),
    sa.Column('name_en', sa.Text(), nullable=True, comment='英文名稱'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('dish',
    sa.Column('dish_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('name_zh', sa.Text(), nullable=False, comment='中文菜名'),
    sa.Column('is_set', sa.Boolean(), nullable=False, comment='是否為套餐'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='顯示排序'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('dish_price',
    sa.Column('price_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dish_id', sa.BigInteger(), nullable=False),
    sa.Column('price_label', sa.Text(), nullable=True, comment='價格標籤(小中大)'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.dish_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_table('dish_translation',
    sa.Column('dish_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False, comment='語言代碼'),
    sa.Column('name', sa.Text(), nullable=False, comment='對應語言菜名'),
    sa.Column('description', sa.Text(), nullable=True, comment='對應語言描述'),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.dish_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dish_id', 'lang')
    )
    op.create_table('set_item',
    sa.Column('set_id', sa.BigInteger(), nullable=False, comment='套餐ID(父菜)'),
    sa.Column('item_id', sa.BigInteger(), nullable=False, comment='子菜ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='數量'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='顯示排序'),
    sa.ForeignKeyConstraint(['item_id'], ['dish.dish_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['set_id'], ['dish.dish_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_item')
    op.drop_table('dish_translation')
    op.drop_table('dish_price')
    op.drop_table('dish')
    op.drop_table('category')
    # ### end Alembic commands ###
